version: '3.7' # https://docs.docker.com/compose/compose-file/compose-versioning/

services:

  # Initialize the DB container:
  #   docker-compose up db
  #   ./bin/rake db:create db:migrate db:seed
  #
  # Destroy all services and their related storage:
  #   docker-compose down --volumes
  db:
    image: postgres:14
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - '127.16.0.1:5432:5432' # 127.16.0.1      pg.tailwind-app.test
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev