dev_test: &dev_test
  adapter: postgresql
  host: pg.tailwind-app.test
  user: postgres
  password: password

development:
  <<: *dev_test
  database: dev

test:
  <<: *dev_test
  database: test

production:
  url: <%= ENV['DATABASE_URL'] %>